### ISSUE TITLE
Feat: 바텀네비게이션바 및 페이지 연동 구현

### ISSUE THREAD

**Issue by world2222** [Hipspot/hipspot-mobile#11]
## Description

- 바텀 네비게이션바 및 각 버튼과 스크린과의 연동을 개발할 예정입니다.

## Todo

- [x] 바텀 네비게이션 바 구현 (지도, 추천, 마이페이지)
- [x] 추천 페이지 구현
- [x] 마이 페이지 구현

## References

- Google을 참고하여 개발합니다.
