### ISSUE TITLE
Feat: api 연동하여 추천 페이지 이미지 띄우기

### ISSUE THREAD

**Issue by world2222** [Hipspot/hipspot-mobile#20]
## Description

- hipspot의 api url을 플러터를 통해 연동하여 추천 페이지 목록에 필요한 이미지들을 띄우는 기능을 구현할 것입니다.
- ImageSlider를 간소화 할 것입니다.

## Todo

- [x] 현재 위치에서 가장 가까운 카페 구현
- [x] 후기가 좋은 카페 구현
- [x] 새로 오픈한 카페 구현
- [x] 위치 권한 요청 띄우고 허용 시 위치 정보 받아 api url에 넣기 구현
- [x] ImageSlier 간소화
## References

- Google을 참고하여 개발합니다.
